packages:
  - "packages/libs"
  - "packages/rslib-plugin"
  - "packages/create-rex-widget"
  - "examples/*"
overrides:
  zod: 4.6.4
allowBuilds:
  core-js: false
minimumReleaseAgeExclude:
  - zod@4.6.4
